import { Inter } from "next/font/google";

import "./globals.css";

import App from "./_app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className="">
        {/* <nav className="flex justify-between w-full px-12 py-4 h-16 bg-gray-300 text-gray-900 text-xl font-semibold">
          <div>Project Drive</div>

          <ul className="flex gap-8 justify-end ">
            <li>
              <a href="#">Home</a>
            </li>
            <li>
              <a href="#">About</a>
            </li>
            <li>
              <a href="#">Contact</a>
            </li>
          </ul>
        </nav> */}

        <main className="">
          <App>{children}</App>
        </main>
      </body>
    </html>
  );
}
